In [37]:
%pip install numpy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [38]:
import numpy as np
a = np.array([0, 1, 2, 3])
print(a)

print(np.arange(10))  # for creating arrays from 0 to 9 using arange function of numpy

L = range(1000)
import timeit
%timeit np.array(L)**2  # numpy array operation

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]
210 μs ± 22.5 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [39]:
a=np.arange(1000)  
%timeit a**2  # numpy array operation

5.24 μs ± 303 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


Creating Array

In [40]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [41]:
a.ndim

1

In [42]:
a.shape

(4,)

In [43]:
len(a)

4

2-D array

In [44]:
b = np.array([[0, 1, 2], 
              [3, 4, 5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [45]:
b.ndim


2

In [46]:
b.shape

(2, 3)

In [47]:
len(b) # size of 1st dimension

2

In [48]:
c =np.array([[[0, 1],
              [2, 3]],
                [[4, 6],
                [7, 8]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 6],
        [7, 8]]])

In [49]:
c.ndim

3

In [50]:
c.shape

(2, 2, 2)

In [51]:
len(c)

2

In [52]:
#using arange function
# aarange is an array-valued version of the built-in Python range function

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
b = np.arange(1,10,2) # start, stop, step
b


array([1, 3, 5, 7, 9])

In [54]:
#using linspace function
a = np.linspace(0, 1, 6) # 6 numbers between 0 and 1
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [55]:
a = np.ones((3, 3)) # array of all ones
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [56]:
a = np.zeros((3, 3)) # array of all zeros
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [57]:
c = np.eye(3) # identity matrix
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
c = np.eye(3,2) # identity matrix
c

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [59]:
a= np.diag([1,2,3,4]) # diagonal matrix
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [60]:
np.diag(a) # extract diagonal

array([1, 2, 3, 4])

In [61]:
a= np.random.rand(4)    # uniform distribution between 0 and 1
a


array([0.49592555, 0.4789764 , 0.69951443, 0.88831972])

In [62]:
a = np.arange(10)
a.dtype

dtype('int64')

In [63]:
a= np.arange(10, dtype='float64')
a.dtype

dtype('float64')

In [64]:
a = np.zeros((3,3))
print(a)
a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [65]:
d = np.array([1+2j, 2+4j]) # complex numbers
d.dtype

dtype('complex128')

In [66]:
b = np.array([True,False,True,False]) # boolean array
print(b.dtype )

bool


Indexing and slicing

In [67]:
a = np.arange(10)
print(a[5])

5


In [68]:
a= np.diag([1,2,3]) # diagonal matrix
print(a)
print(a[2,2])   

[[1 0 0]
 [0 2 0]
 [0 0 3]]
3


In [69]:
a[2,1] = 5 # change an element
print(a)    

[[1 0 0]
 [0 2 0]
 [0 5 3]]


Slicing

In [70]:
a[1:8:2] # slicing  


array([[0, 2, 0]])

In [71]:
a = np.arange(10)
a[5:] = 10  # change elements from index 5 to end
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [72]:
b = np.arange(5)          
a[5:] = b[::-1] # assing
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

Copies and views

In [73]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
b = a[::2] # slicing with step
b

array([0, 2, 4, 6, 8])

In [75]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [76]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [77]:
a=np.arange(10)
c = a[::2].copy() # to avoid changing original array
c

array([0, 2, 4, 6, 8])

In [78]:
c[0] =10
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Fancy Indexing

In [79]:
a = np.random.randint(0, 20, 15) # random integers between 0 and 20
a   

array([ 7, 11,  2,  6,  5,  9,  2, 11, 11, 14, 19, 17,  9, 18,  3],
      dtype=int32)

In [80]:
mask  = (a%2 == 0 )
extract_from_a = a[mask]
extract_from_a


array([ 2,  6,  2, 14, 18], dtype=int32)

Indexing with a mask can be vary usefule to assign a new value to a sub-array:

In [81]:
a[mask] = -1
a   

array([ 7, 11, -1, -1,  5,  9, -1, 11, 11, -1, 19, 17,  9, -1,  3],
      dtype=int32)

Indexing with an arrya of Integers

In [82]:
a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [83]:
# Indexting can be done with an arrya of integers, with the same index is repeated servral time:
a[[2,3,4,2]]

array([20, 30, 40, 20])

In [84]:
# new values can be assigned
a[[9,7]] = -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

#### <span style="color:blue;">Elementwise Operations</span>
**1. Basic Operrations**

with scalars

In [85]:
a = np.array([1, 2, 3, 4]) # create a 1D array
a+1

array([2, 3, 4, 5])

In [86]:
a ** 2

array([ 1,  4,  9, 16])

All arithmectic operations elementwise

In [89]:
b = np.ones(4) + 1
print(b)
print(a)
print(a-b)  # substraction



[2. 2. 2. 2.]
[1 2 3 4]
[-1.  0.  1.  2.]


In [90]:
print(a)
print(b)
a*b

[1 2 3 4]
[2. 2. 2. 2.]


array([2., 4., 6., 8.])

# martix multiplication

In [93]:
c = np.diag([1,2,3,4])
print(c * c)
print("*************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


### comparisions

In [ ]:
#arryawise comparisions
a = np.array([1, 2, 3, 4]) 
b= np.array([5, 2, 2, 4])
print("a==b")
print(a==b)
print("a>b")
print(a>b)

a==b
[False  True False  True]
a>b
[False False  True False]


In [97]:
#arry element wise comparisions
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])
print(np.array_equal(a, b))

False


**logical Operations**

In [98]:
a = np.array([1, 1, 0, 0] , dtype=bool )
a = np.array([1, 0, 1, 0] , dtype=bool )

np.logical_or(a , b)

array([ True,  True,  True,  True])

In [99]:
np.logical_and(a , b)

array([ True, False,  True, False])

**Transcendental funcrion**  Trigonometry

In [100]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [101]:
np.log(a)

C:\Users\sicky\AppData\Local\Temp\ipykernel_15192\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [102]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [103]:
a = np.arange(4)
a + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

## Basic Reductions

In [107]:
x = np.array([1, 2, 3, 4])
print(np.sum(x))

10


In [108]:
# sm by rows and by columns
x = np.array([[1, 1],
              [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [109]:
x.sum(axis=0)  # sum by columns 

array([3, 3])

In [110]:
x.sum(axis=1)  # sum by row

array([2, 4])

**Othere reductions**

In [116]:
x = np.array([1, 3, 2])
print(x.min())

1


In [113]:
print(x.max())

2


In [122]:
print(x.argmin()) # index of min element


0


In [123]:
print(x.argmax()) # index of max element

1


**Logical Opertation**

In [125]:
print(np.all([True, True, False]))


False


In [126]:
print(np.any([True, True, False]))

True


In [127]:
a= np.zeros((50,50))
print(np.any(a != 0))

False


In [131]:
print(np.all(a == a))

True


In [134]:
a = np.array([1, 2, 3 ,2])
b = np.array([2, 2, 3 ,2])
c = np.array([6, 4, 4 ,5])
print ( ((a <=b) & (b <=c) ).all())

True


**Statistics**

In [137]:
x = np.array([1, 2, 3, 1])
y = np.array(([1, 2, 3], [5, 6, 1]))
print(x.mean())

1.75


In [138]:
print(np.median(x))

1.5


In [139]:
np.median(y, axis=1) #last axis

array([2., 5.])

In [140]:
print(x.std())

0.82915619758885


#### Example
Data in populations.txt descript the population of lynexs (and carrot) in northern india during 5 year


In [148]:
data = np.loadtxt('populations.txt', delimiter=',', skiprows=1)
print(data)


[[2020.   30.    4.  500.]
 [2021.   47.    6.  530.]
 [2022.   58.   15.  480.]
 [2023.   43.   23.  470.]
 [2024.   25.    8.  520.]]


In [150]:
year,hares,lynxes,rabbits = data.T # transpose to get each column
print(year)

[2020. 2021. 2022. 2023. 2024.]


In [152]:
#the mean poulation overs time
populations = data[:, 1:]
print(populations)

[[ 30.   4. 500.]
 [ 47.   6. 530.]
 [ 58.  15. 480.]
 [ 43.  23. 470.]
 [ 25.   8. 520.]]


In [153]:
# smaple standard deviation
print(populations.std(axis=0))

[11.87602627  6.96850056 22.8035085 ]


In [154]:
np.argmax(populations, axis=1)

array([2, 2, 2, 2, 2])

### Broadcasting

In [ ]:
a = np.tile(np.arange(0,40,10), (4,1) ) # create a 4x4 array by repeating [0,10,20,30] 4 times
print(a)
print("******************")
a= a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
******************
[[ 0  0  0  0]
 [10 10 10 10]
 [20 20 20 20]
 [30 30 30 30]]


In [164]:
b = np.array([0,0,1,2])
b


array([0, 0, 1, 2])

In [ ]:
print(a + b)

[[ 0  0  1  2]
 [10 10 11 12]
 [20 20 21 22]
 [30 30 31 32]]


In [168]:
a= np.arange(0, 40, 10)
a.shape

(4,)

In [170]:
a = a[:, np.newaxis] # adds a new axis ->2D array
a.shape

(4, 1, 1)

In [171]:
a + b

array([[[ 0,  0,  1,  2]],

       [[10, 10, 11, 12]],

       [[20, 20, 21, 22]],

       [[30, 30, 31, 32]]])

Array shape Manipulation

**Flatterning**


In [173]:
a = np.array([[1,2,3],
              [4,5,6]] )
a.ravel()  # flatten the array

array([1, 2, 3, 4, 5, 6])

In [175]:
a.T # Transpose of the array

array([[1, 4],
       [2, 5],
       [3, 6]])

**Reshape**

In [179]:
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [182]:
b = a.ravel()
print(b)

[1 2 3 4 5 6]


In [183]:
b = b.reshape(2,3)
print(b)

[[1 2 3]
 [4 5 6]]


In [184]:
b[0,0]=100
a

array([[100,   2,   3],
       [  4,   5,   6]])

**Note Reshape may also return a copy**

In [186]:
a = np.zeros((3,2))
b = a.T.reshape(3*2)
b[0] = 50
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

**Adding a dimension**

1D array to 2D array

2D array to 3D array

3D array to 4D array so on

In [188]:
z= np.array([1, 2, 3])
z

array([1, 2, 3])

In [189]:
z[:, np.newaxis]

array([[1],
       [2],
       [3]])


**Dimension shuffling**

In [190]:
a = np.arange(4*3*2).reshape(4,3,2)
a.shape

(4, 3, 2)

In [192]:
print(a)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [193]:
a[0,2,1]

np.int64(5)

**Resizing**

In [197]:
a = np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

**sorting**

In [ ]:
#sorting along an axis
a = np.array([[5,4,6],[2,3,2]])
b =np.sort(a, axis=1) # sort each row
b

array([[4, 5, 6],
       [2, 2, 3]])

In [201]:
# in-place sorting
a.sort(axis=1)
a

array([[4, 5, 6],
       [2, 2, 3]])

In [202]:
#sorting with fancy indexing
a = np.array([4,3,1,2])
j = np.argsort(a)
j

array([2, 3, 1, 0])

In [203]:
a[j]

array([1, 2, 3, 4])