In [25]:
%pip install numpy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [26]:
import numpy as np
a = np.array([0, 1, 2, 3])
print(a)

print(np.arange(10))  # for creating arrays from 0 to 9 using arange function of numpy

L = range(1000)
import timeit
%timeit np.array(L)**2  # numpy array operation

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]
222 μs ± 31.9 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [27]:
a=np.arange(1000)  
%timeit a**2  # numpy array operation

6.76 μs ± 2.54 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


Creating Array

In [28]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [29]:
a.ndim

1

In [30]:
a.shape

(4,)

In [31]:
len(a)

4

2-D array

In [32]:
b = np.array([[0, 1, 2], 
              [3, 4, 5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [33]:
b.ndim


2

In [34]:
b.shape

(2, 3)

In [35]:
len(b) # size of 1st dimension

2

In [36]:
c =np.array([[[0, 1],
              [2, 3]],
                [[4, 6],
                [7, 8]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 6],
        [7, 8]]])

In [37]:
c.ndim

3

In [38]:
c.shape

(2, 2, 2)

In [39]:
len(c)

2

In [40]:
#using arange function
# aarange is an array-valued version of the built-in Python range function

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
b = np.arange(1,10,2) # start, stop, step
b


array([1, 3, 5, 7, 9])

In [42]:
#using linspace function
a = np.linspace(0, 1, 6) # 6 numbers between 0 and 1
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [43]:
a = np.ones((3, 3)) # array of all ones
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
a = np.zeros((3, 3)) # array of all zeros
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
c = np.eye(3) # identity matrix
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
c = np.eye(3,2) # identity matrix
c

array([[1., 0.],
       [0., 1.],
       [0., 0.]])