In [2]:
%pip install numpy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
a = np.array([0, 1, 2, 3])
print(a)

print(np.arange(10))  # for creating arrays from 0 to 9 using arange function of numpy

L = range(1000)
import timeit
%timeit np.array(L)**2  # numpy array operation

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]
194 μs ± 10.2 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [4]:
a=np.arange(1000)  
%timeit a**2  # numpy array operation

5.32 μs ± 1.36 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


Creating Array

In [5]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [6]:
a.ndim

1

In [7]:
a.shape

(4,)

In [8]:
len(a)

4

2-D array

In [9]:
b = np.array([[0, 1, 2], 
              [3, 4, 5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
b.ndim


2

In [11]:
b.shape

(2, 3)

In [12]:
len(b) # size of 1st dimension

2

In [13]:
c =np.array([[[0, 1],
              [2, 3]],
                [[4, 6],
                [7, 8]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 6],
        [7, 8]]])

In [14]:
c.ndim

3

In [15]:
c.shape

(2, 2, 2)

In [16]:
len(c)

2

In [17]:
#using arange function
# aarange is an array-valued version of the built-in Python range function

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
b = np.arange(1,10,2) # start, stop, step
b


array([1, 3, 5, 7, 9])

In [19]:
#using linspace function
a = np.linspace(0, 1, 6) # 6 numbers between 0 and 1
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [20]:
a = np.ones((3, 3)) # array of all ones
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
a = np.zeros((3, 3)) # array of all zeros
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
c = np.eye(3) # identity matrix
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
c = np.eye(3,2) # identity matrix
c

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [24]:
a= np.diag([1,2,3,4]) # diagonal matrix
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [25]:
np.diag(a) # extract diagonal

array([1, 2, 3, 4])

In [26]:
a= np.random.rand(4)    # uniform distribution between 0 and 1
a


array([0.77630904, 0.75405379, 0.41796491, 0.69984347])

In [28]:
a = np.arange(10)
a.dtype

dtype('int64')

In [29]:
a= np.arange(10, dtype='float64')
a.dtype

dtype('float64')

In [32]:
a = np.zeros((3,3))
print(a)
a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [33]:
d = np.array([1+2j, 2+4j]) # complex numbers
d.dtype

dtype('complex128')

In [34]:
b = np.array([True,False,True,False]) # boolean array
print(b.dtype )

bool


Indexing and slicing

In [ ]:
a = np.arange(10)
print(a[5])

5


In [36]:
a= np.diag([1,2,3]) # diagonal matrix
print(a)
print(a[2,2])   

[[1 0 0]
 [0 2 0]
 [0 0 3]]
3


In [37]:
a[2,1] = 5 # change an element
print(a)    

[[1 0 0]
 [0 2 0]
 [0 5 3]]


Slicing

In [38]:
a[1:8:2] # slicing  


array([[0, 2, 0]])

In [ ]:
a = np.arange(10)
a[5:] = 10  # change elements from index 5 to end
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [40]:
b = np.arange(5)          
a[5:] = b[::-1] # assing
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])